version: 2.1

parameters:
  environment:
    type: string
    default: "staging"

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: "Build Application"
          command: |
            echo "Building in << pipeline.parameters.environment >> environment"
  build2:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: "Build Application"
          command: |
            echo "Building in << pipeline.parameters.environment >> environment"         
  test:
    parameters:
      env:
        type: string
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "Deploying to << parameters.env >>"
workflows:
 version: 2
 deployment:
   jobs:
     - build
     - build2:
         environment: "production"
     - test:  # Corrected indentation
         env: test  
